# -*- coding: utf-8 -*-
"""AdventureWorks_Python_Data_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NmeWM7YW-CRjcBo32H56Qa5rh1hEpfI9

# AdventureWorks — Level 1: Beginner Python Data Analysis

## Project: Explore, Clean, Filter, Sort & Understand the Data

### Learning goals
By the end of this notebook, students will be able to:

- Load an Excel workbook into Google Colab
- Explore multiple related Excel sheets
- Understand rows, columns and data types
- Check missing values and duplicates
- Identify and fix a data-quality issue
- Filter records using conditions
- Sort data
- Calculate basic statistics
- Answer simple business questions using Python and pandas

### Business scenario

You are a **Junior Data Analyst** at AdventureWorks.

Management has provided an Excel workbook containing customer, product, sales, return, discount and territory data.

Before building dashboards or performing advanced analysis, your first responsibility is to **understand and prepare the data**.

> **Important:** This is Level 1. We will focus only on exploration, basic cleaning, filtering, sorting and descriptive statistics. Merging, advanced analysis and visualization will come in later levels.

## 1. Import the Required Libraries

We will mainly use:

- **pandas** — working with tabular data
- **numpy** — numerical operations
- **matplotlib** — basic plotting later in the course
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

"""## 2. Upload the Excel File

Run the next cell and upload your `Book1(2).xlsx` file.

The code is designed for Google Colab, so students do not need to know the local file path.

"""

from google.colab import files

uploaded = files.upload()

file_name = next(iter(uploaded))
print("Uploaded file:", file_name)

"""## 3. Read the Excel Workbook

An Excel workbook can contain many sheets.

First, let's find out which sheets are available.

"""

excel_file = pd.ExcelFile(file_name)

print("Sheets available in the workbook:")
for sheet in excel_file.sheet_names:
    print("-", sheet)

"""### Expected workbook structure

The important sheets in this project are:

- Calendar
- Customer
- Discounts
- Product Category
- Product
- Product Subcategory
- Returns
- Sales Data 2020
- Sales Data 2021
- Sales Data 2022
- Territory

`Sheet11` is an auxiliary/unnecessary sheet and will not be used in this Level 1 analysis.

## 4. Load the Important Sheets

For Level 1, we will work mainly with:

- Customer
- Product
- Sales Data 2020
- Sales Data 2021
- Sales Data 2022
- Returns
- Territory

We will bring the other supporting sheets into the workbook later when we study relationships and merging.
"""

customer = pd.read_excel(file_name, sheet_name="Customer")
product = pd.read_excel(file_name, sheet_name="Product")
sales_2020 = pd.read_excel(file_name, sheet_name="Sales Data 2020")
sales_2021 = pd.read_excel(file_name, sheet_name="Sales Data 2021")
sales_2022 = pd.read_excel(file_name, sheet_name="Sales Data 2022")
returns = pd.read_excel(file_name, sheet_name="Returns")
territory = pd.read_excel(file_name, sheet_name="Territory ")

print("Customer:", customer.shape)
print("Product:", product.shape)
print("Sales 2020:", sales_2020.shape)
print("Sales 2021:", sales_2021.shape)
print("Sales 2022:", sales_2022.shape)
print("Returns:", returns.shape)
print("Territory:", territory.shape)

"""# PART A — EXPLORE THE DATA

## 5. Look at the First Few Rows

The first thing an analyst normally does is inspect the data.

### `head()`
Shows the first 5 rows by default.

"""

customer.head()

product.head()

sales_2020.head()

"""### Student Practice

Inspect the first few rows of:

1. `sales_2021`
2. `sales_2022`
3. `returns`
4. `territory`

**Question:** What does one row represent in each table?

"""

# YOUR PRACTICE
# Write your code below.

"""## 6. Look at the Last Few Rows

`tail()` helps us inspect the end of a dataset.

"""

sales_2022.tail()

"""## 7. Find the Number of Rows and Columns

The `.shape` property returns:

`(number of rows, number of columns)`

"""

print("Customer:", customer.shape)
print("Product:", product.shape)
print("Sales 2020:", sales_2020.shape)
print("Sales 2021:", sales_2021.shape)
print("Sales 2022:", sales_2022.shape)

"""### Student Practice

Find the shape of:

- Returns
- Territory
- Customer

Then answer:

**Which table contains the most records?**

"""

# YOUR PRACTICE

"""## 8. View Column Names

Column names tell us what information is available.

"""

print("Customer columns:")
print(customer.columns.tolist())

print("\nProduct columns:")
print(product.columns.tolist())

print("\nSales 2020 columns:")
print(sales_2020.columns.tolist())

"""## 9. Understand Data Types

Different columns contain different types of information.

Examples:

- `int64` → whole numbers
- `float64` → decimal numbers
- `object` → text
- `datetime64` → dates

Let's inspect the Product table.

"""

product.dtypes

"""## 10. Get a Quick Dataset Summary

`info()` gives us:

- Number of rows
- Column names
- Non-null values
- Data types
- Memory information

"""

product.info()

"""### Student Practice

Run `info()` for:

- Customer
- Sales 2020
- Sales 2021
- Sales 2022
- Returns

Look for columns that contain dates, numbers and text.

"""

# YOUR PRACTICE

"""# PART B — DATA CLEANING

## 11. Check for Missing Values

Missing values can affect analysis.

We will count missing values in every column.

"""

customer.isnull().sum()

product.isnull().sum()

sales_2020.isnull().sum()

"""### Student Practice

Check missing values in:

- Sales 2021
- Sales 2022
- Returns

**Question:** Which columns contain missing values?

"""

# YOUR PRACTICE

"""## 12. Check for Duplicate Rows

Duplicate records can produce incorrect results.

First, count duplicate rows.

"""

print("Duplicate rows in Customer:", customer.duplicated().sum())
print("Duplicate rows in Product:", product.duplicated().sum())
print("Duplicate rows in Sales 2020:", sales_2020.duplicated().sum())

"""## 13. Investigate the 2021 Sales Data

During our initial inspection, we found that the 2021 sales sheet has a column named **`C`** where we expect the order date.

Let's inspect the columns.

"""

print(sales_2021.columns.tolist())

"""### Why is this a data-quality problem?

The 2020 and 2022 tables use:

`OrderDate`

but the 2021 table uses:

`C`

The underlying values are dates, so we can correct the column name.

This is a good example of a real-world data-cleaning task.

"""

sales_2021 = sales_2021.rename(columns={"C": "OrderDate"})

print(sales_2021.columns.tolist())

"""## 14. Check the Corrected Date Column

Make sure the values are recognized as dates.

"""

sales_2021["OrderDate"] = pd.to_datetime(sales_2021["OrderDate"], errors="coerce")

print(sales_2021["OrderDate"].dtype)
print(sales_2021["OrderDate"].head())

"""## 15. Check Other Date Columns

Let's make sure the sales date columns are dates.

"""

sales_2020["OrderDate"] = pd.to_datetime(sales_2020["OrderDate"], errors="coerce")
sales_2022["OrderDate"] = pd.to_datetime(sales_2022["OrderDate"], errors="coerce")
returns["ReturnDate"] = pd.to_datetime(returns["ReturnDate"], errors="coerce")

print("Sales 2020:", sales_2020["OrderDate"].dtype)
print("Sales 2021:", sales_2021["OrderDate"].dtype)
print("Sales 2022:", sales_2022["OrderDate"].dtype)
print("Returns:", returns["ReturnDate"].dtype)

"""## 16. Check for Invalid Dates

`errors="coerce"` converts invalid date values into missing values (`NaT`).

Now we can check whether any invalid dates exist.

"""

print("Invalid Sales 2020 dates:", sales_2020["OrderDate"].isna().sum())
print("Invalid Sales 2021 dates:", sales_2021["OrderDate"].isna().sum())
print("Invalid Sales 2022 dates:", sales_2022["OrderDate"].isna().sum())
print("Invalid Return dates:", returns["ReturnDate"].isna().sum())

"""### Cleaning checkpoint

At this stage, students should be able to explain:

1. Why we inspect column names
2. Why missing values matter
3. Why duplicates matter
4. Why data types matter
5. Why the 2021 `C` column needed attention

# PART C — FILTERING DATA

## 17. Why Do Analysts Filter Data?

Filtering allows us to answer specific questions.

Examples:

- Which products cost more than $1,000?
- Which customers have income above $100,000?
- Which sales have quantity greater than 5?
- Which records belong to a particular territory?

Let's begin with a simple condition.
"""

high_price_products = product[product["ProductPrice"] > 1000]

high_price_products.head()

"""## 18. Filter Customers by Income

Find customers whose annual income is greater than 100,000.

"""

high_income_customers = customer[customer["AnnualIncome"] > 100000]

high_income_customers.head()

"""## 19. Filter Sales by Order Quantity

Find sales transactions where more than 5 units were ordered.

"""

large_quantity_orders = sales_2022[sales_2022["OrderQuantity"] > 5]

large_quantity_orders.head()

"""## 20. Filter Using Multiple Conditions

We can combine conditions.

Example business question:

> Find customers with annual income above 100,000 AND who own a home.

"""

high_income_homeowners = customer[
    (customer["AnnualIncome"] > 100000) &
    (customer["HomeOwner"] == "Y")
]

high_income_homeowners.head()

"""## 21. Filter Using OR

Example:

> Find customers who are in the Professional OR Management occupation.

"""

selected_occupations = customer[
    (customer["Occupation"] == "Professional") |
    (customer["Occupation"] == "Management")
]

selected_occupations.head()

"""## 22. Filter Text Values

Let's find products that are red.

"""

red_products = product[product["ProductColor"] == "Red"]

red_products[["ProductName", "ProductColor", "ProductPrice"]].head()

"""### Student Practice — Filtering

Answer these questions using pandas:

1. Find products with `ProductPrice` greater than 500.
2. Find customers with `AnnualIncome` less than 50,000.
3. Find sales from 2022 where `OrderQuantity` is greater than 3.
4. Find customers whose `Gender` is `F`.
5. Find products with `ProductColor` equal to `Black`.

Do not modify the original DataFrames.

"""

# YOUR PRACTICE

"""# PART D — SORTING DATA

## 23. Sort Products by Price

Sorting helps us identify highest and lowest values quickly.

"""

product.sort_values("ProductPrice", ascending=False).head(10)

"""## 24. Find the Cheapest Products

Sort from lowest to highest price.

"""

product.sort_values("ProductPrice", ascending=True).head(10)

"""## 25. Sort Customers by Income

Find the customers with the highest annual income.

"""

customer.sort_values("AnnualIncome", ascending=False).head(10)

"""## 26. Sort Sales by Order Quantity

Find transactions with the highest order quantities.

"""

sales_2022.sort_values("OrderQuantity", ascending=False).head(10)

"""## 27. Sort by Multiple Columns

We can sort using more than one column.

Example:

1. Sort by product color
2. Within each color, sort by price from high to low

"""

product.sort_values(
    by=["ProductColor", "ProductPrice"],
    ascending=[True, False]
).head(20)

"""### Student Practice — Sorting

1. Find the 10 most expensive products.
2. Find the 10 cheapest products.
3. Find the 10 customers with the highest annual income.
4. Find the 10 largest 2022 orders by quantity.
5. Sort customers by `EducationLevel` and then by `AnnualIncome` descending.

"""

# YOUR PRACTICE

"""# PART E — BASIC STATISTICS

## 28. Descriptive Statistics

Basic statistics help us understand numerical data.

Important measures include:

- Count
- Mean
- Standard deviation
- Minimum
- 25th percentile
- Median
- 75th percentile
- Maximum

"""

product[["ProductCost", "ProductPrice"]].describe()

"""## 29. Customer Income Statistics

Let's understand the distribution of annual income.

"""

customer["AnnualIncome"].describe()

"""## 30. Sales Quantity Statistics

Let's understand order quantities.

"""

sales_2022["OrderQuantity"].describe()

"""## 31. Individual Statistics

We can calculate individual measures as well.

"""

print("Average product price:", product["ProductPrice"].mean())
print("Minimum product price:", product["ProductPrice"].min())
print("Maximum product price:", product["ProductPrice"].max())
print("Median product price:", product["ProductPrice"].median())

"""## 32. Count Unique Values

Unique values are useful for understanding categories and IDs.

"""

print("Unique customers:", customer["CustomerKey"].nunique())
print("Unique products:", product["ProductKey"].nunique())
print("Unique customer occupations:", customer["Occupation"].nunique())
print("Unique product colors:", product["ProductColor"].nunique())

"""## 33. Frequency Counts with value_counts()

This tells us how frequently each category appears.

"""

print("Customer gender:")
print(customer["Gender"].value_counts())

print("\nCustomer occupation:")
print(customer["Occupation"].value_counts())

print("\nProduct color:")
print(product["ProductColor"].value_counts())

"""# PART F — SIMPLE BUSINESS QUESTIONS

Now let's use what we learned to answer practical questions.

## Question 1
How many products are available?

"""

number_of_products = product["ProductKey"].nunique()
print("Number of unique products:", number_of_products)

"""## Question 2
What is the average product price?

"""

average_product_price = product["ProductPrice"].mean()
print(f"Average product price: ${average_product_price:,.2f}")

"""## Question 3
What is the most expensive product?

"""

most_expensive_product = product.loc[product["ProductPrice"].idxmax(),
                                         ["ProductName", "ProductPrice"]]

most_expensive_product

"""## Question 4
What is the cheapest product?

"""

cheapest_product = product.loc[product["ProductPrice"].idxmin(),
                                     ["ProductName", "ProductPrice"]]

cheapest_product

"""## Question 5
What is the average annual income of customers?

"""

average_income = customer["AnnualIncome"].mean()
print(f"Average annual customer income: ${average_income:,.2f}")

"""## Question 6
How many total units were ordered in each sales year?

This is still a basic calculation; we are not merging tables yet.

"""

print("2020 units:", sales_2020["OrderQuantity"].sum())
print("2021 units:", sales_2021["OrderQuantity"].sum())
print("2022 units:", sales_2022["OrderQuantity"].sum())

"""## Question 7
How many sales transactions are present in each year?

"""

print("2020 transactions:", len(sales_2020))
print("2021 transactions:", len(sales_2021))
print("2022 transactions:", len(sales_2022))

"""# PART G — MINI ANALYST CHALLENGE

Try to solve the following questions **without looking at a solution first**.

### Customer Analysis
1. How many customers are there?
2. What is the average annual income?
3. What is the highest annual income?
4. Which occupation appears most frequently?
5. How many customers are homeowners?

### Product Analysis
6. How many products are there?
7. What is the average product price?
8. What is the highest product price?
9. What is the average product cost?
10. Which product color appears most frequently?

### Sales Analysis
11. Which year has the highest number of sales records?
12. Which year has the highest total order quantity?
13. What is the maximum order quantity in 2022?
14. How many unique customers appear in 2022?
15. How many unique products appear in 2022?

### Data Quality
16. Are there duplicate customer rows?
17. Are there missing values in the Product table?
18. Does the 2021 sales table use the same order-date column name as 2020 and 2022?
19. What data type is the 2021 `OrderDate` column after cleaning?

### Analyst Thinking
20. Write **three observations** you can make from your analysis.

> **Important:** An observation should be based on a number or result from the data. Do not write assumptions that cannot be supported by the dataset.

"""

# MINI ANALYST CHALLENGE
# Write your solutions below.

"""# PART H — LEVEL 1 FINAL CHECKLIST

Before moving to Level 2, make sure you can explain these concepts in your own words:

- [ ] What is a DataFrame?
- [ ] How do you read an Excel sheet?
- [ ] What does `.shape` tell you?
- [ ] What does `.head()` do?
- [ ] What does `.info()` tell you?
- [ ] How do you identify missing values?
- [ ] How do you identify duplicates?
- [ ] Why are data types important?
- [ ] How do you rename a column?
- [ ] How do you filter rows?
- [ ] How do you apply multiple filter conditions?
- [ ] How do you sort data?
- [ ] What is mean?
- [ ] What is median?
- [ ] What does `describe()` provide?
- [ ] What does `value_counts()` do?
- [ ] What is the difference between a row count and a unique count?

## Level 1 outcome

You have now completed the first stage of a real data-analysis workflow:

**Explore → Clean → Filter → Sort → Describe → Answer Questions**

In **Level 2**, we can use this same workbook to teach:

**Concatenation → Merge/Join → GroupBy → Aggregation → Date Analysis → KPI creation**

"""

